# Generated by Django 3.1.7 on 2021-04-27 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UIC_LEARNING', '0004_logindetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='logindetails',
        ),
    ]
